In [1]:
train = pd.read_csv("data/train_new2.csv").set_index('VisitNumber')
test = pd.read_csv("data/test_new2.csv").set_index('VisitNumber')

In [2]:
train.head()

,Weekday,ScanCount,FinelineNumber,Count,Min,Max,Mean,Range,Null_Depts,Neg_Count,...,TOYS,OPTICAL,PHARMACY,CLOTHES,GROCERIES,HOME,JEWELRY AND ACCESSORIES,HOUSEHOLD GOODS,BEAUTY AND PERSONAL CARE,TripType
VisitNumber,,,,,,,,,,,,,,,,,,,,,
5,4,-1,1000,0,0,0,0.000000,0,0,1,...,0,0,0,0,0,0,0,0,0,999
7,4,1,8931,1,1,1,1.000000,0,0,0,...,0,0,0,1,0,0,0,0,1,30
8,4,3,9999,3,1,20,4.833333,19,1,1,...,0,0,0,0,3,0,0,1,0,26
9,4,1,5501,1,1,2,1.500000,1,0,0,...,0,0,0,0,2,0,0,0,0,8
10,4,1,7950,1,1,2,1.500000,1,0,0,...,0,0,0,0,2,0,0,0,0,8

In [3]:
train2 = pd.read_csv("data/train_new(dropFN).csv").set_index('VisitNumber')

In [4]:
train["TripType"] = train2["TripType"]

In [5]:
train.head()

,Weekday,ScanCount,FinelineNumber,Count,Min,Max,Mean,Range,Null_Depts,Neg_Count,...,TOYS,OPTICAL,PHARMACY,CLOTHES,GROCERIES,HOME,JEWELRY AND ACCESSORIES,HOUSEHOLD GOODS,BEAUTY AND PERSONAL CARE,TripType
VisitNumber,,,,,,,,,,,,,,,,,,,,,
5,4,-1,1000,0,0,0,0.000000,0,0,1,...,0,0,0,0,0,0,0,0,0,37
7,4,1,8931,1,1,1,1.000000,0,0,0,...,0,0,0,1,0,0,0,0,1,22
8,4,3,9999,3,1,20,4.833333,19,1,1,...,0,0,0,0,3,0,0,1,0,18
9,4,1,5501,1,1,2,1.500000,1,0,0,...,0,0,0,0,2,0,0,0,0,5
10,4,1,7950,1,1,2,1.500000,1,0,0,...,0,0,0,0,2,0,0,0,0,5

In [7]:
test.head()

,Weekday,ScanCount,FinelineNumber,Count,Min,Max,Mean,Range,Null_Depts,Neg_Count,...,SPORTING GOODS,TOYS,OPTICAL,PHARMACY,CLOTHES,GROCERIES,HOME,JEWELRY AND ACCESSORIES,HOUSEHOLD GOODS,BEAUTY AND PERSONAL CARE
VisitNumber,,,,,,,,,,,,,,,,,,,,,
1,4,1,3555,1,1,2,1.333333,1,0,0,...,0,0,0,0,1,3,0,0,0,0
2,4,1,8023,1,1,2,1.333333,1,0,0,...,0,0,0,0,0,2,0,0,0,0
3,4,1,4504,1,1,1,1.000000,0,0,1,...,0,0,0,0,0,0,0,0,0,2
4,4,1,5924,1,1,1,1.000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,4,1,654,1,1,1,1.000000,0,0,1,...,0,0,0,0,2,0,0,0,0,0

In [6]:
len(train), len(test)

(95674, 95674)

In [10]:
a = train.columns.unique()
b = test.columns.unique()
set(a) - set(b)

{'TripType'}

In [11]:
train_col = train.drop(['TripType'], axis=1)
dfX = train_col
dfy = train.TripType

In [13]:
import xgboost as xgb
from sklearn.cross_validation import train_test_split
from sklearn.metrics import log_loss

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(dfX, dfy, test_size=0.25)

In [15]:
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# 1.

In [ ]:
param = {
    'max_depth': 3,  # the maximum depth of each tree
    'eta': 0.3,  # the training step for each iteration
    'silent': 1,  # logging mode - quiet
    'objective': 'multi:softmax',  # error evaluation for multiclass training
    'num_class': 38}  # the number of classes that exist in this datset
num_round = 20  # the number of training iterations

In [ ]:
import xgboost as xgb
from sklearn.cross_validation import train_test_split
from sklearn.metrics import log_loss

In [16]:
mytrain, mytest = train_test_split(train, test_size = .4)

In [17]:
mytrain_ = mytrain.drop(['TripType'], axis=1)
mytest_ = mytest.drop(['TripType'], axis=1)

In [18]:
dtrain = xgb.DMatrix(np.asarray(mytrain_), label = np.asarray(mytrain.TripType))
dtest = xgb.DMatrix(np.asarray(mytest_), label = np.asarray(mytest.TripType))

In [19]:
num_round = 200
param1 = {'max_depth': 3, 'eta': 0.3, 'objective': 'multi:softmax', 'num_class':38, "max_delta_step": 1}
watchlist1 = [(dtrain,'train'), (dtest, 'eval')]

bst = xgb.train(param1, dtrain, num_round, watchlist1, early_stopping_rounds=5)

[0]	train-merror:0.675772	eval-merror:0.673112
Multiple eval metrics have been passed: 'eval-merror' will be used for early stopping.

Will train until eval-merror hasn't improved in 5 rounds.
[1]	train-merror:0.61055	eval-merror:0.606114
[2]	train-merror:0.552366	eval-merror:0.551555
[3]	train-merror:0.465455	eval-merror:0.46496
[4]	train-merror:0.416243	eval-merror:0.417011
[5]	train-merror:0.400895	eval-merror:0.401202
[6]	train-merror:0.395565	eval-merror:0.396891
[7]	train-merror:0.391088	eval-merror:0.392866
[8]	train-merror:0.388684	eval-merror:0.390227
[9]	train-merror:0.384346	eval-merror:0.387431
[10]	train-merror:0.376768	eval-merror:0.380272
[11]	train-merror:0.363198	eval-merror:0.366632
[12]	train-merror:0.361229	eval-merror:0.363392
[13]	train-merror:0.35616	eval-merror:0.359342
[14]	train-merror:0.353756	eval-merror:0.356101
[15]	train-merror:0.349836	eval-merror:0.352783
[16]	train-merror:0.347032	eval-merror:0.34983
[17]	train-merror:0.345202	eval-merror:0.348759
[18]	train-merror:0.343338	eval-merror:0.346198
[19]	train-merror:0.33921	eval-merror:0.343559
[20]	train-merror:0.337938	eval-merror:0.342984
[21]	train-merror:0.336335	eval-merror:0.342461
[22]	train-merror:0.335168	eval-merror:0.34139
[23]	train-merror:0.334663	eval-merror:0.340136
[24]	train-merror:0.333165	eval-merror:0.339927
[25]	train-merror:0.331946	eval-merror:0.338803
[26]	train-merror:0.329524	eval-merror:0.337262
[27]	train-merror:0.329507	eval-merror:0.337235
[28]	train-merror:0.328305	eval-merror:0.336791
[29]	train-merror:0.32597	eval-merror:0.334727
[30]	train-merror:0.325622	eval-merror:0.334387
[31]	train-merror:0.324472	eval-merror:0.333577
[32]	train-merror:0.322608	eval-merror:0.331617
[33]	train-merror:0.321249	eval-merror:0.330703
[34]	train-merror:0.319838	eval-merror:0.329841
[35]	train-merror:0.318845	eval-merror:0.329318
[36]	train-merror:0.318392	eval-merror:0.3289
[37]	train-merror:0.317539	eval-merror:0.328665
[38]	train-merror:0.316476	eval-merror:0.329057
[39]	train-merror:0.314821	eval-merror:0.328142
[40]	train-merror:0.313915	eval-merror:0.327437
[41]	train-merror:0.31301	eval-merror:0.326496
[42]	train-merror:0.311686	eval-merror:0.325817
[43]	train-merror:0.310484	eval-merror:0.325163
[44]	train-merror:0.310066	eval-merror:0.324745
[45]	train-merror:0.308393	eval-merror:0.324092
[46]	train-merror:0.307958	eval-merror:0.323987
[47]	train-merror:0.3074	eval-merror:0.323778
[48]	train-merror:0.306494	eval-merror:0.324353
[49]	train-merror:0.305798	eval-merror:0.323726
[50]	train-merror:0.304665	eval-merror:0.323308
[51]	train-merror:0.303655	eval-merror:0.322785
[52]	train-merror:0.303028	eval-merror:0.32289
[53]	train-merror:0.30193	eval-merror:0.322211
[54]	train-merror:0.301146	eval-merror:0.320956
[55]	train-merror:0.300989	eval-merror:0.320904
[56]	train-merror:0.29977	eval-merror:0.320617
[57]	train-merror:0.299544	eval-merror:0.320852
[58]	train-merror:0.298864	eval-merror:0.321035
[59]	train-merror:0.297802	eval-merror:0.320512
[60]	train-merror:0.297627	eval-merror:0.320355
[61]	train-merror:0.296756	eval-merror:0.319911
[62]	train-merror:0.295241	eval-merror:0.31931
[63]	train-merror:0.294701	eval-merror:0.319153
[64]	train-merror:0.293917	eval-merror:0.319049
[65]	train-merror:0.293638	eval-merror:0.318631
[66]	train-merror:0.292697	eval-merror:0.318631
[67]	train-merror:0.2916	eval-merror:0.318213
[68]	train-merror:0.290938	eval-merror:0.317821
[69]	train-merror:0.290032	eval-merror:0.317298
[70]	train-merror:0.288882	eval-merror:0.317194
[71]	train-merror:0.28836	eval-merror:0.316593
[72]	train-merror:0.287663	eval-merror:0.316828
[73]	train-merror:0.287071	eval-merror:0.317063
[74]	train-merror:0.286827	eval-merror:0.317246
[75]	train-merror:0.285991	eval-merror:0.316357
[76]	train-merror:0.285555	eval-merror:0.316044
[77]	train-merror:0.284318	eval-merror:0.315443
[78]	train-merror:0.284005	eval-merror:0.315391
[79]	train-merror:0.283534	eval-merror:0.315286
[80]	train-merror:0.283186	eval-merror:0.315103
[81]	train-merror:0.282576	eval-merror:0.315338
[82]	train-merror:0.281966	eval-merror:0.314868
[83]	train-merror:0.28174	eval-merror:0.31526
[84]	train-merror:0.281217	eval-merror:0.315025
[85]	train-merror:0.280486	eval-merror:0.314711
[86]	train-merror:0.279963	eval-merror:0.314267
[87]	train-merror:0.27958	eval-merror:0.313771
[88]	train-merror:0.278918	eval-merror:0.314136
[89]	train-merror:0.278778	eval-merror:0.314267
[90]	train-merror:0.277263	eval-merror:0.313614
[91]	train-merror:0.276392	eval-merror:0.313509
[92]	train-merror:0.275695	eval-merror:0.313065
[93]	train-merror:0.27472	eval-merror:0.312987
[94]	train-merror:0.274354	eval-merror:0.31249
[95]	train-merror:0.273518	eval-merror:0.312124
[96]	train-merror:0.272612	eval-merror:0.312281
[97]	train-merror:0.271688	eval-merror:0.311785
[98]	train-merror:0.271096	eval-merror:0.311628
[99]	train-merror:0.270573	eval-merror:0.31155
[100]	train-merror:0.270434	eval-merror:0.311131
[101]	train-merror:0.270277	eval-merror:0.311131
[102]	train-merror:0.269493	eval-merror:0.3104
[103]	train-merror:0.268936	eval-merror:0.310112
[104]	train-merror:0.268535	eval-merror:0.309825
[105]	train-merror:0.267821	eval-merror:0.309642
[106]	train-merror:0.267211	eval-merror:0.309825
[107]	train-merror:0.267002	eval-merror:0.310008
[108]	train-merror:0.266793	eval-merror:0.309877
[109]	train-merror:0.266636	eval-merror:0.309747
[110]	train-merror:0.265818	eval-merror:0.309459
[111]	train-merror:0.265887	eval-merror:0.309172
[112]	train-merror:0.265365	eval-merror:0.309041
[113]	train-merror:0.26479	eval-merror:0.308675
[114]	train-merror:0.264668	eval-merror:0.308832
[115]	train-merror:0.263832	eval-merror:0.308832
[116]	train-merror:0.263274	eval-merror:0.308832
[117]	train-merror:0.262456	eval-merror:0.30844
[118]	train-merror:0.261585	eval-merror:0.3081
[119]	train-merror:0.261132	eval-merror:0.308022
[120]	train-merror:0.26033	eval-merror:0.30797
[121]	train-merror:0.259686	eval-merror:0.308074
[122]	train-merror:0.259442	eval-merror:0.307865
[123]	train-merror:0.259041	eval-merror:0.3081
[124]	train-merror:0.258815	eval-merror:0.308309
[125]	train-merror:0.258362	eval-merror:0.308179
[126]	train-merror:0.257891	eval-merror:0.308126
[127]	train-merror:0.257682	eval-merror:0.307917
Stopping. Best iteration:
[122]	train-merror:0.259442	eval-merror:0.307865

In [20]:
my_test = xgb.DMatrix(np.asarray(mytest_))
test_predictions = bst.predict(my_test).astype(int)

In [21]:
from sklearn.metrics import *
print(classification_report(np.array(mytest.TripType), test_predictions))

             precision    recall  f1-score   support

          0       0.86      0.98      0.92      1490
          1       0.85      0.54      0.66       135
          2       0.78      0.85      0.81      1863
          3       0.80      0.82      0.81       516
          4       0.62      0.52      0.56      2339
          5       0.80      0.88      0.84      4891
          6       0.74      0.86      0.80      3812
          7       0.20      0.02      0.03       108
          8       0.00      0.00      0.00         3
          9       0.62      0.47      0.54       388
         10       0.44      0.42      0.43       230
         11       0.56      0.51      0.54       138
         12       0.62      0.64      0.63       258
         13       0.71      0.66      0.68       273
         14       0.52      0.52      0.52       344
         15       0.70      0.65      0.67        49
         16       0.62      0.62      0.62      1064
         17       0.61      0.73      0.67      1520
         18       0.52      0.51      0.51       187
         19       0.62      0.61      0.62       309
         20       0.53      0.54      0.53       199
         21       0.57      0.49      0.53       173
         22       0.45      0.15      0.22       409
         23       0.76      0.77      0.77       220
         24       0.64      0.69      0.67       779
         25       0.64      0.57      0.60       546
         26       0.64      0.61      0.62       300
         27       0.54      0.50      0.52       782
         28       0.66      0.65      0.66      1223
         29       0.48      0.21      0.30      1061
         30       0.49      0.21      0.29      1208
         31       0.53      0.71      0.60      3921
         32       0.76      0.91      0.83      2482
         33       0.20      0.06      0.09       214
         34       0.45      0.33      0.38       742
         35       0.21      0.05      0.08       331
         36       0.42      0.24      0.30       446
         37       0.94      0.79      0.86      3317

avg / total       0.68      0.69      0.68     38270

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [22]:
walmart_test = xgb.DMatrix(np.asarray(test))
prediction_xgb3 = bst.predict(walmart_test)

In [23]:
prediction_xgb3 = prediction_xgb3.astype(int)

In [24]:
set(prediction_xgb3)

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37}

In [25]:
def prediction_to_csv(prediction):
    df_VN = pd.DataFrame(columns=["VisitNumber"])
    df_VN["VisitNumber"] = test.index
    df_TT = pd.DataFrame(columns=["TripType"])
    df_TT["TripType"] = prediction
    df_TT = pd.get_dummies(df_TT.TripType).astype(int, cbopy=False)
    df_TT = df_TT.rename(columns = {0:"TripType_3", 1: "TripType_4", 2: "TripType_5", 3: "TripType_6", 
                4: "TripType_7", 5: "TripType_8", 6: "TripType_9", 7: "TripType_12", 8: "TripType_14", 
                9: "TripType_15", 10: "TripType_18", 11: "TripType_19", 12: "TripType_20", 13: "TripType_21",
                14: "TripType_22", 15: "TripType_23", 16: "TripType_24", 17: "TripType_25", 18: "TripType_26", 
                19: "TripType_27", 20: "TripType_28", 21: "TripType_29", 22: "TripType_30", 23: "TripType_31", 
                24: "TripType_32", 25: "TripType_33", 26: "TripType_34", 27: "TripType_35", 28: "TripType_36", 
                29: "TripType_37", 30: "TripType_38", 31: "TripType_39", 32: "TripType_40", 33: "TripType_41", 
                34: "TripType_42", 35: "TripType_43", 36: "TripType_44", 37: "TripType_999"})
    trial = pd.concat([df_VN, df_TT], axis=1).set_index('VisitNumber')
    #trial["TripType_4"] = 0
    trial["TripType_14"] = 0
    return trial.to_csv("data/trial_8.csv")

In [26]:
prediction_to_csv(prediction_xgb3)